services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      - SERVICES=backup,iam,sts,cloudwatch,events,secretsmanager
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=us-east-1
    volumes:
      - "${PWD}/.localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/workspace
    working_dir: /workspace
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOST=localstack
      - AWS_ENDPOINT=http://localstack:4566
    depends_on:
      - localstack
    entrypoint: ["/bin/sh", "-c"]
    command: ["while true; do sleep 1000; done"]  # Keep container running
