version: 2.1

executors:
  terraform:
    docker:
    - image: hashicorp/terraform:light
jobs:
  terraform-format-check:
    executor: terraform
    steps:
    - checkout
    - run:
        name: Check terraform formatting
        command: |
          terraform fmt -recursive -check
workflows:
  version: 2
  branch_workflow:
    jobs:
    - terraform-format-check
