name: 'Integration Tests'
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

defaults:
  run:
    shell: 'bash'

permissions:
  contents: read
  id-token: write

jobs:
  format:
    runs-on: 'ubuntu-latest'
    steps:
      # Checkout the code
      - name: 'checkout'
        uses: 'actions/checkout@v3'
      # Install Terraform
      - name: 'Install Terraform'
        uses: 'hashicorp/setup-terraform@v2'
        with:
          terraform_version: '1.9.5'
      # Check the Terraform formatting
      - name: 'check formatting'
        run: |
          terraform fmt -check -recursive
