name: 'Integration Tests'

env:
  TERRAFORM_VERSION: 1.12.0

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

defaults:
  run:
    shell: 'bash'

permissions:
  contents: read
  id-token: write

jobs:
  format:
    runs-on: 'ubuntu-latest'
    steps:
      # Checkout the code
      - name: 'checkout'
        uses: 'actions/checkout@v3'
      # Install Terraform with proper permissions
      - name: 'Install Terraform'
        run: |
          wget https://releases.hashicorp.com/terraform/${{ env.TERRAFORM_VERSION }}/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          unzip terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          chmod +x terraform
          sudo mv terraform /usr/local/bin/
      # Check the Terraform formatting
      - name: 'check formatting'
        run: |
          terraform fmt -check -recursive
  validate:
    runs-on: 'ubuntu-latest'
    steps:
      # Checkout the code
      - name: 'checkout'
        uses: 'actions/checkout@v3'
      # Install Terraform with proper permissions
      - name: 'Install Terraform'
        run: |
          wget https://releases.hashicorp.com/terraform/${{ env.TERRAFORM_VERSION }}/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          unzip terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          chmod +x terraform
          sudo mv terraform /usr/local/bin/
      # Validate the module can compile
      - name: 'validate module'
        run: |
          cd tests
          terraform init
          terraform validate          
          
  spellcheck:
    runs-on: 'ubuntu-latest'
    steps:
      # Checkout the code
      - name: 'checkout'
        uses: 'actions/checkout@v3'
      # Perform a spellcheck on the markdown files
      # https://github.com/marketplace/actions/github-spellcheck-action
      - name: 'Spellcheck'
        uses: 'rojopolis/spellcheck-github-actions@0.33.0'
        with:
          source_files: 'CHANGELOG.md CONTRIBUTING.md LICENSE.md README.md'
          task_name: 'Markdown'

  test:
    name: 'Run Terraform Tests'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v3'
      
      - name: 'Install Terraform'
        run: |
          wget https://releases.hashicorp.com/terraform/${{ env.TERRAFORM_VERSION }}/terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          unzip terraform_${{ env.TERRAFORM_VERSION }}_linux_amd64.zip
          chmod +x terraform
          sudo mv terraform /usr/local/bin/
      
      - name: 'Run Terraform Tests'
        working-directory: './tests'
        run: |
          terraform init
          terraform test
